---
- hosts: localhost
  connection: local
  tasks:
  - name: Add prometheus chart repo
    kubernetes.core.helm_repository:
      name: prometheus
      repo_url: "https://prometheus-community.github.io/helm-charts"
  - name: Deploy latest version of Prometheus chart inside prometheus namespace
    kubernetes.core.helm:
      name: prometheus
      chart_ref: prometheus-community/prometheus
      release_namespace: prometheus
      create_namespace: true
      values_files:
        - monitoring/prometheus/values.yaml