---
- hosts: localhost
  connection: local
  tasks:
  - name: Add grafana chart repo
    kubernetes.core.helm_repository:
      name: grafana
      repo_url: "https://grafana.github.io/helm-charts"
  - name: Deploy latest version of Prometheus chart inside prometheus namespace
    kubernetes.core.helm:
      name: grafana
      chart_ref: grafana/grafana
      release_namespace: grafana
      create_namespace: true
      values_files:
        - monitoring/grafana/values.yaml